# Generated by Django 3.0.5 on 2020-04-23 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Granja', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='hierro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idIronCode', models.CharField(max_length=20)),
                ('Img', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='propietario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=100)),
                ('Telefono', models.CharField(max_length=10)),
                ('IdGranja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Granja.granja')),
                ('IdHierro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Granjero.hierro')),
            ],
        ),
    ]
