# Generated by Django 3.0.5 on 2020-04-27 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Granjero', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hierro',
            name='image',
            field=models.ImageField(default='gallery/static/images/no-img.jpg', upload_to='hierro/'),
        ),
        migrations.AddField(
            model_name='propietario',
            name='image',
            field=models.ImageField(default='gallery/static/images/no-img.jpg', upload_to='propietarios/'),
        ),
    ]
