# Generated by Django 3.0.5 on 2020-04-29 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Granjero', '0003_auto_20200427_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hierro',
            name='Img',
        ),
    ]
