# Generated by Django 3.0.5 on 2020-05-01 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Animal', '0005_auto_20200501_1122'),
        ('Granjero', '0004_remove_hierro_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propietario',
            old_name='image',
            new_name='imagePropietario',
        ),
        migrations.RemoveField(
            model_name='propietario',
            name='IdHierro',
        ),
        migrations.AddField(
            model_name='propietario',
            name='imageHierro',
            field=models.ImageField(default='gallery/static/images/no-img.jpg', upload_to='hierro/'),
        ),
        migrations.DeleteModel(
            name='hierro',
        ),
    ]
