# Generated by Django 3.0.5 on 2020-04-19 01:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Animal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassTrans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clase', models.CharField(max_length=30)),
                ('Detalle', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='serviInsu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo', models.CharField(max_length=30)),
                ('Nombre', models.CharField(max_length=30)),
                ('Valor_Unidad', models.FloatField()),
                ('Detalle', models.CharField(max_length=100)),
                ('Proveedor', models.CharField(max_length=30)),
                ('Telefono', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TypeTrans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo', models.CharField(max_length=30)),
                ('Detalle', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date(2020, 4, 18))),
                ('detail', models.CharField(max_length=100)),
                ('Value', models.FloatField()),
                ('quantity', models.FloatField()),
                ('AnimalCode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Animal.animal')),
                ('TypeTrans', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trans.TypeTrans')),
                ('classTrans', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trans.ClassTrans')),
            ],
        ),
    ]
