# Generated by Django 3.0.5 on 2020-04-19 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassTransInsServ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clase', models.CharField(max_length=30)),
                ('Detalle', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='serviinsu',
            name='Tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trans.ClassTransInsServ'),
        ),
    ]
