# Generated by Django 3.0.5 on 2020-05-11 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Granja', '0004_granja_user'),
        ('trans', '0004_auto_20200427_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='IdGranja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Granja.granja'),
        ),
    ]
