# Generated by Django 3.0.5 on 2020-04-19 01:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Granjero', '0001_initial'),
        ('Granja', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='concepto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=30)),
                ('detalle_concepto', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='etapa_productiva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa_prod', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='genero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='proposito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_proposito', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='raza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raza', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('Valor_inicial', models.FloatField()),
                ('Codigo_animal', models.CharField(max_length=50)),
                ('Fecha_recibida', models.DateField(default=datetime.date(2020, 4, 18))),
                ('Fecha_nacimiento', models.DateField()),
                ('Código_mama', models.CharField(blank=True, max_length=20, null=True)),
                ('Código_papa', models.CharField(blank=True, max_length=20, null=True)),
                ('Etapa_productiva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Animal.etapa_productiva')),
                ('Genero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Animal.genero')),
                ('Hierro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Granjero.hierro')),
                ('IdGranja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Granja.granja')),
                ('Proposito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Animal.proposito')),
                ('Raza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Animal.raza')),
                ('concepto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Animal.concepto')),
            ],
        ),
    ]
