# Generated by Django 3.0.5 on 2020-04-24 16:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Animal', '0002_auto_20200424_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='Fecha_recibida',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
