# Generated by Django 3.0.5 on 2020-04-27 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Animal', '0003_auto_20200424_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='image',
            field=models.ImageField(default='gallery/static/images/no-img.jpg', upload_to='Animales/'),
        ),
    ]
