# Generated by Django 3.0.5 on 2020-05-01 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Granjero', '0004_remove_hierro_img'),
        ('Animal', '0004_animal_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='Hierro',
        ),
        migrations.AddField(
            model_name='animal',
            name='propietario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Granjero.propietario'),
        ),
    ]
