# Generated by Django 3.0.5 on 2020-06-13 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Animal', '0006_animal_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='Codigo_animal',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
