# Generated by Django 3.0.5 on 2020-06-27 15:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Animal', '0007_auto_20200613_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='Fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='Fecha_recibida',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
