# Generated by Django 3.0.5 on 2020-07-28 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Animal', '0008_auto_20200627_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='estado',
            field=models.CharField(default='', max_length=50),
        ),
    ]
