# Generated by Django 3.0.5 on 2020-04-25 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Granja', '0002_auto_20200425_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='granja',
            name='image',
            field=models.ImageField(default='gallery/static/images/no-img.jpg', upload_to='granja/'),
        ),
    ]
